[package]
name = "percolator-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
pinocchio = { workspace = true }

[features]
default = []
